name: "build-test"

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm ci
          npm test
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create maven settings.xml
        uses: ./
        with:
          servers: '[{"id": "foo", "username": "fu", "password": "bar" }]'
          mirrors: '[{ "id": "nexus", "mirrorOf": "!my-org-snapshots,*", "url": "http://redacted/nexus/content/groups/public" }]'
          repositories: '[{"id": "foo", "url": "https://fu.bar"}]'
          plugin_repositories: '[{"id": "foo-plugin", "url": "https://fu.bar.plugin"}]'
          profiles: '[{ "id": "foo.profile", "name": "foo.profile", "url": "http://foo.bar.profile", "properties": { "foo": "property-1", "bar": "property-2"} }]'
          plugin_groups: '[ "some.plugin.group.id", "some.other.plugin.group.id" ]'
      - run: |
          cat ~/.m2/settings.xml

